### ISSUE TITLE
How to install at arm64 linux

### ISSUE THREAD

**Issue by zhangxingjing** [SBGit-2019/Pyside-QCP#7]
At arm64 linux, can not install pyside2 and shiboken2 by pip, so I installed these by apt-get.But I found that there is no shiboken2-generator so I can not compile qcustomplot-pyside2.Is there some method to install qcustomplot-pyside2 at arm64 linux?

**Comment by zhangxingjing** [comment]
I successfully build this repo at arm64 linux. Refrence:[Build Pyside2](https://forums.raspberrypi.com/viewtopic.php?p=2053969)

**Comment by SBGit-2019** [comment]
Thank you for the nice work. I close this issue and moved you linked to the WIKI pages here.
